spring.application.name=authentification
server.port=8080
spring.config.import=optional:consul:
security.jwt.issuer=auth-service
security.jwt.expiration-minutes=15
spring.cloud.consul.host=${SPRING_CLOUD_CONSUL_HOST:localhost}
spring.cloud.consul.port=${SPRING_CLOUD_CONSUL_PORT:8500}
spring.cloud.consul.discovery.register=true
spring.cloud.consul.discovery.prefer-ip-address=true

# dev local
jwt.key.private-path=./keys/private_key.pem
jwt.key.public-path=./keys/public_key.pem
